namespace AwqatSalaat.Helpers
{
    public static class CalendarPalettes
    {
        public static CalendarDocumentPalette[] Palettes { get; } = new CalendarDocumentPalette[]
        {
            new CalendarDocumentPalette
            {
                Group = "Light",
                Name = "Black",
                DocumentBackground = "#FFFFFF",
                SectionBackground = "#202024",
                SectionForeground = "#FFFFFF",
                SectionBorder = "#BAA272",
                SectionOverlayBackground = "#07FFFFFF",
                SectionOverlayForeground = "#FFFFFF",
                SectionOverlayBorder = "#BAA272",
                TableForeground = "#1F1F1F",
                TableBorder = "#D1BA8C",
                TableHeaderBackground = "#BAA272",
                TableHeaderForeground = "#FFFFFF",
                TableRowSeparator = "#D3D3D3",
                HighlightForeground = "#F2CC80",
            },
            new CalendarDocumentPalette
            {
                Group = "Light",
                Name = "Blue",
                DocumentBackground = "#FFFFFF",
                SectionBackground = "#2F3F4F",
                SectionForeground = "#FFFFFF",
                SectionBorder = "#BAA272",
                SectionOverlayBackground = "#07FFFFFF",
                SectionOverlayForeground = "#FFFFFF",
                SectionOverlayBorder = "#BAA272",
                TableForeground = "#1F1F2F",
                TableBorder = "#D1BA8C",
                TableHeaderBackground = "#BAA272",
                TableHeaderForeground = "#FFFFFF",
                TableRowSeparator = "#D3D3D3",
                HighlightForeground = "#F2CC80",
            },
            new CalendarDocumentPalette
            {
                Group = "Light",
                Name = "Brown",
                DocumentBackground = "#FFFFFF",
                SectionBackground = "#332C29",
                SectionForeground = "#FFFFFF",
                SectionBorder = "#BAA272",
                SectionOverlayBackground = "#07FFFFFF",
                SectionOverlayForeground = "#FFFFFF",
                SectionOverlayBorder = "#BAA272",
                TableForeground = "#1F1F1F",
                TableBorder = "#D1BA8C",
                TableHeaderBackground = "#BAA272",
                TableHeaderForeground = "#FFFFFF",
                TableRowSeparator = "#D3D3D3",
                HighlightForeground = "#F2CC80",
            },
            new CalendarDocumentPalette
            {
                Group = "Light",
                Name = "Olive Green",
                DocumentBackground = "#FFFFFF",
                SectionBackground = "#CAD9C3",
                SectionForeground = "#1F1F1F",
                SectionBorder = "#404840",
                SectionOverlayBackground = "#07000000",
                SectionOverlayForeground = "#1F1F1F",
                SectionOverlayBorder = "#00e2f2da",
                TableForeground = "#1F1F1F",
                TableBorder = "#404840",
                TableHeaderBackground = "#404840",
                TableHeaderForeground = "#FFFFFF",
                TableRowSeparator = "#CAD9C3",
                HighlightForeground = "#404840",
            },
            new CalendarDocumentPalette
            {
                Group = "Light",
                Name = "Gray",
                DocumentBackground = "#FFFFFF",
                SectionBackground = "#F0F0F0",
                SectionForeground = "#3F3F3F",
                SectionBorder = "#4A4746",
                SectionOverlayBackground = "#4A4746",
                SectionOverlayForeground = "#FFFFFF",
                SectionOverlayBorder = "#00000000",
                TableForeground = "#1F1F1F",
                TableBorder = "#4A4746",
                TableHeaderBackground = "#4A4746",
                TableHeaderForeground = "#FFFFFF",
                TableRowSeparator = "#F0F0F0",
                HighlightForeground = "#1A1918",
            },
            new CalendarDocumentPalette
            {
                Group = "Light",
                Name = "Tafsir Center",
                DocumentBackground = "#FFFFFF",
                SectionBackground = "#5F743B",
                SectionForeground = "#FFFFFF",
                SectionBorder = "#B6985A",
                SectionOverlayBackground = "#B6985A",
                SectionOverlayForeground = "#FFFFFF",
                SectionOverlayBorder = "#FFFFFF",
                TableForeground = "#1F2F1F",
                TableBorder = "#5F743B",
                TableHeaderBackground = "#B6985A",
                TableHeaderForeground = "#FFFFFF",
                TableRowSeparator = "#E8E8E0",
                HighlightForeground = "#F2CC80",
            },
            new CalendarDocumentPalette
            {
                Group = "High Contrast",
                Name = "Black & White",
                DocumentBackground = "#FFFFFF",
                SectionBackground = "#000000",
                SectionForeground = "#FFFFFF",
                SectionBorder = "#000000",
                SectionOverlayBackground = "#000000",
                SectionOverlayForeground = "#FFFFFF",
                SectionOverlayBorder = "#000000",
                TableForeground = "#000000",
                TableBorder = "#000000",
                TableHeaderBackground = "#000000",
                TableHeaderForeground = "#FFFFFF",
                TableRowSeparator = "#000000",
                HighlightForeground = "#FFFFFF",
            },
        };
    }
}
