//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwqatSalaat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AwqatSalaat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awqat Salaat.
        /// </summary>
        public static string Data_AppName {
            get {
                return ResourceManager.GetString("Data.AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asr.
        /// </summary>
        public static string Data_Salaat_Asr {
            get {
                return ResourceManager.GetString("Data.Salaat.Asr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhuhr.
        /// </summary>
        public static string Data_Salaat_Dhuhr {
            get {
                return ResourceManager.GetString("Data.Salaat.Dhuhr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farjr.
        /// </summary>
        public static string Data_Salaat_Fajr {
            get {
                return ResourceManager.GetString("Data.Salaat.Fajr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isha.
        /// </summary>
        public static string Data_Salaat_Isha {
            get {
                return ResourceManager.GetString("Data.Salaat.Isha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maghrib.
        /// </summary>
        public static string Data_Salaat_Maghrib {
            get {
                return ResourceManager.GetString("Data.Salaat.Maghrib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string UI_Controls_Toggle_Off {
            get {
                return ResourceManager.GetString("UI.Controls.Toggle.Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string UI_Controls_Toggle_On {
            get {
                return ResourceManager.GetString("UI.Controls.Toggle.On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correspond to.
        /// </summary>
        public static string UI_Panel_CorrespondTo {
            get {
                return ResourceManager.GetString("UI.Panel.CorrespondTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        public static string UI_Panel_Dismiss {
            get {
                return ResourceManager.GetString("UI.Panel.Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string UI_Panel_Error {
            get {
                return ResourceManager.GetString("UI.Panel.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string UI_Panel_Refresh {
            get {
                return ResourceManager.GetString("UI.Panel.Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing....
        /// </summary>
        public static string UI_Panel_Refreshing {
            get {
                return ResourceManager.GetString("UI.Panel.Refreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string UI_Panel_Settings {
            get {
                return ResourceManager.GetString("UI.Panel.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string UI_Settings_Cancel {
            get {
                return ResourceManager.GetString("UI.Settings.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string UI_Settings_Confirm {
            get {
                return ResourceManager.GetString("UI.Settings.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country code.
        /// </summary>
        public static string UI_Settings_CountryCode {
            get {
                return ResourceManager.GetString("UI.Settings.CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It consist of two alphabet letters. (e.g. DZ points to Algeria).
        /// </summary>
        public static string UI_Settings_CountryCodeDescription {
            get {
                return ResourceManager.GetString("UI.Settings.CountryCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string UI_Settings_Language {
            get {
                return ResourceManager.GetString("UI.Settings.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language used for display.
        /// </summary>
        public static string UI_Settings_LanguageDescription {
            get {
                return ResourceManager.GetString("UI.Settings.LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation Method.
        /// </summary>
        public static string UI_Settings_Method {
            get {
                return ResourceManager.GetString("UI.Settings.Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The calculation method which uses longitude, latitude and sun inclination along with other inputs.
        /// </summary>
        public static string UI_Settings_MethodDescription {
            get {
                return ResourceManager.GetString("UI.Settings.MethodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remainder offset.
        /// </summary>
        public static string UI_Settings_RemainderOffset {
            get {
                return ResourceManager.GetString("UI.Settings.RemainderOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of minutes before the time of the next salaat at which notification start. Value 0 disables the notifications..
        /// </summary>
        public static string UI_Settings_RemainderOffsetDescription {
            get {
                return ResourceManager.GetString("UI.Settings.RemainderOffsetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show countdown.
        /// </summary>
        public static string UI_Settings_ShowCountdown {
            get {
                return ResourceManager.GetString("UI.Settings.ShowCountdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select whether to show the countdown near the time of the next salaat on the taskbar.
        /// </summary>
        public static string UI_Settings_ShowCountdownDescription {
            get {
                return ResourceManager.GetString("UI.Settings.ShowCountdownDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        public static string UI_Settings_ZipCode {
            get {
                return ResourceManager.GetString("UI.Settings.ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This code is used to identify the city. Different countries have different formats..
        /// </summary>
        public static string UI_Settings_ZipCodeDescription {
            get {
                return ResourceManager.GetString("UI.Settings.ZipCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        public static string UI_Summary_After {
            get {
                return ResourceManager.GetString("UI.Summary.After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured.
        /// </summary>
        public static string UI_Summary_ErrorOccured {
            get {
                return ResourceManager.GetString("UI.Summary.ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing....
        /// </summary>
        public static string UI_Summary_Refreshing {
            get {
                return ResourceManager.GetString("UI.Summary.Refreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to start.
        /// </summary>
        public static string UI_Summary_TapToStart {
            get {
                return ResourceManager.GetString("UI.Summary.TapToStart", resourceCulture);
            }
        }
    }
}
