//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwqatSalaat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AwqatSalaat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple Islamic Windows widget to show the time of the next prayer alongside a countdown on the taskbar.
        /// </summary>
        public static string Data_AppDescription {
            get {
                return ResourceManager.GetString("Data.AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awqat Salaat.
        /// </summary>
        public static string Data_AppName {
            get {
                return ResourceManager.GetString("Data.AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hanafi.
        /// </summary>
        public static string Data_JuristicSchool_Hanafi {
            get {
                return ResourceManager.GetString("Data.JuristicSchool.Hanafi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard (Shafi, Hanbali, Maliki).
        /// </summary>
        public static string Data_JuristicSchool_Standard {
            get {
                return ResourceManager.GetString("Data.JuristicSchool.Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asr.
        /// </summary>
        public static string Data_Salaat_Asr {
            get {
                return ResourceManager.GetString("Data.Salaat.Asr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhuhr.
        /// </summary>
        public static string Data_Salaat_Dhuhr {
            get {
                return ResourceManager.GetString("Data.Salaat.Dhuhr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fajr.
        /// </summary>
        public static string Data_Salaat_Fajr {
            get {
                return ResourceManager.GetString("Data.Salaat.Fajr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isha.
        /// </summary>
        public static string Data_Salaat_Isha {
            get {
                return ResourceManager.GetString("Data.Salaat.Isha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maghrib.
        /// </summary>
        public static string Data_Salaat_Maghrib {
            get {
                return ResourceManager.GetString("Data.Salaat.Maghrib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuruq.
        /// </summary>
        public static string Data_Salaat_Shuruq {
            get {
                return ResourceManager.GetString("Data.Salaat.Shuruq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string UI_About_Contact {
            get {
                return ResourceManager.GetString("UI.About.Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Project.
        /// </summary>
        public static string UI_About_VisitProject {
            get {
                return ResourceManager.GetString("UI.About.VisitProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string UI_ContextMenu_Hide {
            get {
                return ResourceManager.GetString("UI.ContextMenu.Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string UI_ContextMenu_Quit {
            get {
                return ResourceManager.GetString("UI.ContextMenu.Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-position.
        /// </summary>
        public static string UI_ContextMenu_Reposition {
            get {
                return ResourceManager.GetString("UI.ContextMenu.Reposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string UI_ContextMenu_Show {
            get {
                return ResourceManager.GetString("UI.ContextMenu.Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string UI_Controls_Toggle_Off {
            get {
                return ResourceManager.GetString("UI.Controls.Toggle.Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string UI_Controls_Toggle_On {
            get {
                return ResourceManager.GetString("UI.Controls.Toggle.On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correspond to.
        /// </summary>
        public static string UI_Panel_CorrespondTo {
            get {
                return ResourceManager.GetString("UI.Panel.CorrespondTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        public static string UI_Panel_Dismiss {
            get {
                return ResourceManager.GetString("UI.Panel.Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string UI_Panel_Error {
            get {
                return ResourceManager.GetString("UI.Panel.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string UI_Panel_Refresh {
            get {
                return ResourceManager.GetString("UI.Panel.Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing....
        /// </summary>
        public static string UI_Panel_Refreshing {
            get {
                return ResourceManager.GetString("UI.Panel.Refreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string UI_Panel_Settings {
            get {
                return ResourceManager.GetString("UI.Panel.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string UI_Settings_Browse {
            get {
                return ResourceManager.GetString("UI.Settings.Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string UI_Settings_Cancel {
            get {
                return ResourceManager.GetString("UI.Settings.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string UI_Settings_Check {
            get {
                return ResourceManager.GetString("UI.Settings.Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking....
        /// </summary>
        public static string UI_Settings_Checking {
            get {
                return ResourceManager.GetString("UI.Settings.Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string UI_Settings_City {
            get {
                return ResourceManager.GetString("UI.Settings.City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the city.
        /// </summary>
        public static string UI_Settings_CityDescription {
            get {
                return ResourceManager.GetString("UI.Settings.CityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string UI_Settings_Confirm {
            get {
                return ResourceManager.GetString("UI.Settings.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country code.
        /// </summary>
        public static string UI_Settings_CountryCode {
            get {
                return ResourceManager.GetString("UI.Settings.CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It consist of two alphabet letters. (e.g. DZ points to Algeria).
        /// </summary>
        public static string UI_Settings_CountryCodeDescription {
            get {
                return ResourceManager.GetString("UI.Settings.CountryCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time period.
        /// </summary>
        public static string UI_Settings_ElapsedPeriod {
            get {
                return ResourceManager.GetString("UI.Settings.ElapsedPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of minutes for which a notification is run after the salaat time has entered. Value 0 disables the notification..
        /// </summary>
        public static string UI_Settings_ElapsedPeriodDescription {
            get {
                return ResourceManager.GetString("UI.Settings.ElapsedPeriodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact mode.
        /// </summary>
        public static string UI_Settings_EnableCompactMode {
            get {
                return ResourceManager.GetString("UI.Settings.EnableCompactMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make the widget smaller and take less space.
        /// </summary>
        public static string UI_Settings_EnableCompactModeDescription {
            get {
                return ResourceManager.GetString("UI.Settings.EnableCompactModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string UI_Settings_File {
            get {
                return ResourceManager.GetString("UI.Settings.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juristic school.
        /// </summary>
        public static string UI_Settings_JuristicSchool {
            get {
                return ResourceManager.GetString("UI.Settings.JuristicSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asr jurisdiction method.
        /// </summary>
        public static string UI_Settings_JuristicSchoolDescription {
            get {
                return ResourceManager.GetString("UI.Settings.JuristicSchoolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string UI_Settings_Language {
            get {
                return ResourceManager.GetString("UI.Settings.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language used for display.
        /// </summary>
        public static string UI_Settings_LanguageDescription {
            get {
                return ResourceManager.GetString("UI.Settings.LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string UI_Settings_Latitude {
            get {
                return ResourceManager.GetString("UI.Settings.Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latitude of the city.
        /// </summary>
        public static string UI_Settings_LatitudeDescription {
            get {
                return ResourceManager.GetString("UI.Settings.LatitudeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch on Windows startup.
        /// </summary>
        public static string UI_Settings_LaunchOnWindowsStartup {
            get {
                return ResourceManager.GetString("UI.Settings.LaunchOnWindowsStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow the widget to start running when Windows start.
        /// </summary>
        public static string UI_Settings_LaunchOnWindowsStartupDescription {
            get {
                return ResourceManager.GetString("UI.Settings.LaunchOnWindowsStartupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific coordinates.
        /// </summary>
        public static string UI_Settings_LocationByCoordinates {
            get {
                return ResourceManager.GetString("UI.Settings.LocationByCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect location from manually provided coordinates.
        /// </summary>
        public static string UI_Settings_LocationByCoordinatesDescription {
            get {
                return ResourceManager.GetString("UI.Settings.LocationByCoordinatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Parameters.
        /// </summary>
        public static string UI_Settings_LocationByCountryCode {
            get {
                return ResourceManager.GetString("UI.Settings.LocationByCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the minimum necessary parameters for services to detect location.
        /// </summary>
        public static string UI_Settings_LocationByCountryCodeDescription {
            get {
                return ResourceManager.GetString("UI.Settings.LocationByCountryCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Query.
        /// </summary>
        public static string UI_Settings_LocationByQuery {
            get {
                return ResourceManager.GetString("UI.Settings.LocationByQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for location by address or city name.
        /// </summary>
        public static string UI_Settings_LocationByQueryDescription {
            get {
                return ResourceManager.GetString("UI.Settings.LocationByQueryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type city name or address.
        /// </summary>
        public static string UI_Settings_LocationByQueryHint {
            get {
                return ResourceManager.GetString("UI.Settings.LocationByQueryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string UI_Settings_Longitude {
            get {
                return ResourceManager.GetString("UI.Settings.Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The longitude of the city.
        /// </summary>
        public static string UI_Settings_LongitudeDescription {
            get {
                return ResourceManager.GetString("UI.Settings.LongitudeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation method.
        /// </summary>
        public static string UI_Settings_Method {
            get {
                return ResourceManager.GetString("UI.Settings.Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The calculation method which uses longitude, latitude and sun inclination along with other inputs.
        /// </summary>
        public static string UI_Settings_MethodDescription {
            get {
                return ResourceManager.GetString("UI.Settings.MethodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string UI_Settings_MinutesShort {
            get {
                return ResourceManager.GetString("UI.Settings.MinutesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result.
        /// </summary>
        public static string UI_Settings_NoResult {
            get {
                return ResourceManager.GetString("UI.Settings.NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification sound.
        /// </summary>
        public static string UI_Settings_NotificationSound {
            get {
                return ResourceManager.GetString("UI.Settings.NotificationSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play sound when the notification is active.
        /// </summary>
        public static string UI_Settings_NotificationSoundDescription {
            get {
                return ResourceManager.GetString("UI.Settings.NotificationSoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by.
        /// </summary>
        public static string UI_Settings_PoweredBy {
            get {
                return ResourceManager.GetString("UI.Settings.PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder offset.
        /// </summary>
        public static string UI_Settings_ReminderOffset {
            get {
                return ResourceManager.GetString("UI.Settings.ReminderOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of minutes before the time of the next salaat at which notification start. Value 0 disables the notification..
        /// </summary>
        public static string UI_Settings_ReminderOffsetDescription {
            get {
                return ResourceManager.GetString("UI.Settings.ReminderOffsetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string UI_Settings_Searching {
            get {
                return ResourceManager.GetString("UI.Settings.Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service provider.
        /// </summary>
        public static string UI_Settings_ServiceProvider {
            get {
                return ResourceManager.GetString("UI.Settings.ServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service which provides data of prayer times.
        /// </summary>
        public static string UI_Settings_ServiceProviderDescription {
            get {
                return ResourceManager.GetString("UI.Settings.ServiceProviderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show countdown.
        /// </summary>
        public static string UI_Settings_ShowCountdown {
            get {
                return ResourceManager.GetString("UI.Settings.ShowCountdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select whether to show the countdown near the time of the next salaat on the taskbar.
        /// </summary>
        public static string UI_Settings_ShowCountdownDescription {
            get {
                return ResourceManager.GetString("UI.Settings.ShowCountdownDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show seconds.
        /// </summary>
        public static string UI_Settings_ShowSeconds {
            get {
                return ResourceManager.GetString("UI.Settings.ShowSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select whether to show seconds in countdown.
        /// </summary>
        public static string UI_Settings_ShowSecondsDescription {
            get {
                return ResourceManager.GetString("UI.Settings.ShowSecondsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string UI_Settings_Tabs_About {
            get {
                return ResourceManager.GetString("UI.Settings.Tabs.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string UI_Settings_Tabs_General {
            get {
                return ResourceManager.GetString("UI.Settings.Tabs.General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string UI_Settings_Tabs_Location {
            get {
                return ResourceManager.GetString("UI.Settings.Tabs.Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string UI_Settings_Tabs_Service {
            get {
                return ResourceManager.GetString("UI.Settings.Tabs.Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        public static string UI_Settings_ZipCode {
            get {
                return ResourceManager.GetString("UI.Settings.ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This code is used to identify the city. Different countries have different formats..
        /// </summary>
        public static string UI_Settings_ZipCodeDescription {
            get {
                return ResourceManager.GetString("UI.Settings.ZipCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        public static string UI_Summary_After {
            get {
                return ResourceManager.GetString("UI.Summary.After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured.
        /// </summary>
        public static string UI_Summary_ErrorOccured {
            get {
                return ResourceManager.GetString("UI.Summary.ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing....
        /// </summary>
        public static string UI_Summary_Refreshing {
            get {
                return ResourceManager.GetString("UI.Summary.Refreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since.
        /// </summary>
        public static string UI_Summary_Since {
            get {
                return ResourceManager.GetString("UI.Summary.Since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to start.
        /// </summary>
        public static string UI_Summary_TapToStart {
            get {
                return ResourceManager.GetString("UI.Summary.TapToStart", resourceCulture);
            }
        }
    }
}
