//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwqatSalaat.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsConfigured {
            get {
                return ((bool)(this["IsConfigured"]));
            }
            set {
                this["IsConfigured"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CountryCode {
            get {
                return ((string)(this["CountryCode"]));
            }
            set {
                this["CountryCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZipCode {
            get {
                return ((string)(this["ZipCode"]));
            }
            set {
                this["ZipCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MWL")]
        public global::AwqatSalaat.Services.SalahHour.SalahHourMethod Method {
            get {
                return ((global::AwqatSalaat.Services.SalahHour.SalahHourMethod)(this["Method"]));
            }
            set {
                this["Method"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCountdown {
            get {
                return ((bool)(this["ShowCountdown"]));
            }
            set {
                this["ShowCountdown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public ushort NotificationDistance {
            get {
                return ((ushort)(this["NotificationDistance"]));
            }
            set {
                this["NotificationDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DisplayLanguage {
            get {
                return ((string)(this["DisplayLanguage"]));
            }
            set {
                this["DisplayLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string City {
            get {
                return ((string)(this["City"]));
            }
            set {
                this["City"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MWL")]
        public global::AwqatSalaat.Services.AlAdhan.AlAdhanMethod Method2 {
            get {
                return ((global::AwqatSalaat.Services.AlAdhan.AlAdhanMethod)(this["Method2"]));
            }
            set {
                this["Method2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SalahHour")]
        public global::AwqatSalaat.Data.PrayerTimesService Service {
            get {
                return ((global::AwqatSalaat.Data.PrayerTimesService)(this["Service"]));
            }
            set {
                this["Service"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LaunchOnWindowsStartup {
            get {
                return ((bool)(this["LaunchOnWindowsStartup"]));
            }
            set {
                this["LaunchOnWindowsStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MethodString {
            get {
                return ((string)(this["MethodString"]));
            }
            set {
                this["MethodString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Latitude {
            get {
                return ((decimal)(this["Latitude"]));
            }
            set {
                this["Latitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Longitude {
            get {
                return ((decimal)(this["Longitude"]));
            }
            set {
                this["Longitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Standard")]
        public global::AwqatSalaat.Data.School School {
            get {
                return ((global::AwqatSalaat.Data.School)(this["School"]));
            }
            set {
                this["School"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ByCountryCode")]
        public global::AwqatSalaat.Data.LocationDetectionMode LocationDetection {
            get {
                return ((global::AwqatSalaat.Data.LocationDetectionMode)(this["LocationDetection"]));
            }
            set {
                this["LocationDetection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowSeconds {
            get {
                return ((bool)(this["ShowSeconds"]));
            }
            set {
                this["ShowSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseCompactMode {
            get {
                return ((bool)(this["UseCompactMode"]));
            }
            set {
                this["UseCompactMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte NotificationDistanceElapsed {
            get {
                return ((byte)(this["NotificationDistanceElapsed"]));
            }
            set {
                this["NotificationDistanceElapsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sounds\\birds_chirping.mp3")]
        public string NotificationSoundFile {
            get {
                return ((string)(this["NotificationSoundFile"]));
            }
            set {
                this["NotificationSoundFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableNotificationSound {
            get {
                return ((bool)(this["EnableNotificationSound"]));
            }
            set {
                this["EnableNotificationSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UmAlQura")]
        public global::AwqatSalaat.Data.CalendarType CalendarType {
            get {
                return ((global::AwqatSalaat.Data.CalendarType)(this["CalendarType"]));
            }
            set {
                this["CalendarType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HijriAdjustment {
            get {
                return ((int)(this["HijriAdjustment"]));
            }
            set {
                this["HijriAdjustment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int CustomPosition {
            get {
                return ((int)(this["CustomPosition"]));
            }
            set {
                this["CustomPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AdhanSoundFile {
            get {
                return ((string)(this["AdhanSoundFile"]));
            }
            set {
                this["AdhanSoundFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AdhanFajrSoundFile {
            get {
                return ((string)(this["AdhanFajrSoundFile"]));
            }
            set {
                this["AdhanFajrSoundFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::AwqatSalaat.Data.AdhanSound AdhanSound {
            get {
                return ((global::AwqatSalaat.Data.AdhanSound)(this["AdhanSound"]));
            }
            set {
                this["AdhanSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public sbyte Config_Fajr_Adjustment {
            get {
                return ((sbyte)(this["Config_Fajr_Adjustment"]));
            }
            set {
                this["Config_Fajr_Adjustment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public ushort Config_Fajr_ReminderOffset {
            get {
                return ((ushort)(this["Config_Fajr_ReminderOffset"]));
            }
            set {
                this["Config_Fajr_ReminderOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte Config_Fajr_ElapsedTime {
            get {
                return ((byte)(this["Config_Fajr_ElapsedTime"]));
            }
            set {
                this["Config_Fajr_ElapsedTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Config_Fajr_GlobalReminderOffset {
            get {
                return ((bool)(this["Config_Fajr_GlobalReminderOffset"]));
            }
            set {
                this["Config_Fajr_GlobalReminderOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Config_Fajr_GlobalElapsedTime {
            get {
                return ((bool)(this["Config_Fajr_GlobalElapsedTime"]));
            }
            set {
                this["Config_Fajr_GlobalElapsedTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Config_Shuruq_IsVisible {
            get {
                return ((bool)(this["Config_Shuruq_IsVisible"]));
            }
            set {
                this["Config_Shuruq_IsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public sbyte Config_Shuruq_Adjustment {
            get {
                return ((sbyte)(this["Config_Shuruq_Adjustment"]));
            }
            set {
                this["Config_Shuruq_Adjustment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public sbyte Config_Dhuhr_Adjustment {
            get {
                return ((sbyte)(this["Config_Dhuhr_Adjustment"]));
            }
            set {
                this["Config_Dhuhr_Adjustment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public ushort Config_Dhuhr_ReminderOffset {
            get {
                return ((ushort)(this["Config_Dhuhr_ReminderOffset"]));
            }
            set {
                this["Config_Dhuhr_ReminderOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte Config_Dhuhr_ElapsedTime {
            get {
                return ((byte)(this["Config_Dhuhr_ElapsedTime"]));
            }
            set {
                this["Config_Dhuhr_ElapsedTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Config_Dhuhr_GlobalReminderOffset {
            get {
                return ((bool)(this["Config_Dhuhr_GlobalReminderOffset"]));
            }
            set {
                this["Config_Dhuhr_GlobalReminderOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Config_Dhuhr_GlobalElapsedTime {
            get {
                return ((bool)(this["Config_Dhuhr_GlobalElapsedTime"]));
            }
            set {
                this["Config_Dhuhr_GlobalElapsedTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public sbyte Config_Asr_Adjustment {
            get {
                return ((sbyte)(this["Config_Asr_Adjustment"]));
            }
            set {
                this["Config_Asr_Adjustment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public ushort Config_Asr_ReminderOffset {
            get {
                return ((ushort)(this["Config_Asr_ReminderOffset"]));
            }
            set {
                this["Config_Asr_ReminderOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte Config_Asr_ElapsedTime {
            get {
                return ((byte)(this["Config_Asr_ElapsedTime"]));
            }
            set {
                this["Config_Asr_ElapsedTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Config_Asr_GlobalReminderOffset {
            get {
                return ((bool)(this["Config_Asr_GlobalReminderOffset"]));
            }
            set {
                this["Config_Asr_GlobalReminderOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Config_Asr_GlobalElapsedTime {
            get {
                return ((bool)(this["Config_Asr_GlobalElapsedTime"]));
            }
            set {
                this["Config_Asr_GlobalElapsedTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public sbyte Config_Maghrib_Adjustment {
            get {
                return ((sbyte)(this["Config_Maghrib_Adjustment"]));
            }
            set {
                this["Config_Maghrib_Adjustment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public ushort Config_Maghrib_ReminderOffset {
            get {
                return ((ushort)(this["Config_Maghrib_ReminderOffset"]));
            }
            set {
                this["Config_Maghrib_ReminderOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte Config_Maghrib_ElapsedTime {
            get {
                return ((byte)(this["Config_Maghrib_ElapsedTime"]));
            }
            set {
                this["Config_Maghrib_ElapsedTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Config_Maghrib_GlobalReminderOffset {
            get {
                return ((bool)(this["Config_Maghrib_GlobalReminderOffset"]));
            }
            set {
                this["Config_Maghrib_GlobalReminderOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Config_Maghrib_GlobalElapsedTime {
            get {
                return ((bool)(this["Config_Maghrib_GlobalElapsedTime"]));
            }
            set {
                this["Config_Maghrib_GlobalElapsedTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public sbyte Config_Isha_Adjustment {
            get {
                return ((sbyte)(this["Config_Isha_Adjustment"]));
            }
            set {
                this["Config_Isha_Adjustment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public ushort Config_Isha_ReminderOffset {
            get {
                return ((ushort)(this["Config_Isha_ReminderOffset"]));
            }
            set {
                this["Config_Isha_ReminderOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte Config_Isha_ElapsedTime {
            get {
                return ((byte)(this["Config_Isha_ElapsedTime"]));
            }
            set {
                this["Config_Isha_ElapsedTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Config_Isha_GlobalReminderOffset {
            get {
                return ((bool)(this["Config_Isha_GlobalReminderOffset"]));
            }
            set {
                this["Config_Isha_GlobalReminderOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Config_Isha_GlobalElapsedTime {
            get {
                return ((bool)(this["Config_Isha_GlobalElapsedTime"]));
            }
            set {
                this["Config_Isha_GlobalElapsedTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableLogs {
            get {
                return ((bool)(this["EnableLogs"]));
            }
            set {
                this["EnableLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableDebugLogs {
            get {
                return ((bool)(this["EnableDebugLogs"]));
            }
            set {
                this["EnableDebugLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoAlignment {
            get {
                return ((bool)(this["AutoAlignment"]));
            }
            set {
                this["AutoAlignment"] = value;
            }
        }
    }
}
